### ISSUE TITLE
Nominators could not unstake after collator stoped.

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/DIP-7#33]
### Runtime set storage, set hub admin owner to echo
```
key:
  account: 0x7558016Cdc5B16FF05f46eE83b9b220c9115e883 
  slot: 0x0000000000000000000000000000000000000000000000000000000000000000
  storage_key: 0x1da53b775b270400e7e61ed5cbc5a146ab1160471b1418779239ba8e2b847e4297c3fa06c75514f95993df9f363b02507558016cdc5b16ff05f46ee83b9b220c9115e883ff0f22492f44bac4c4b30ae58d0e8daa0000000000000000000000000000000000000000000000000000000000000000
value:
   0x0000000000000000000000000f14341a7f464320319025540e8fe48ad0fe5aec
```
### Echo run migrate script and transfer hub admin owner back to RingDAO.
